#pragma once

#define INDEX_TEMPERATURE 0
#define INDEX_HUMIDITY 1
#define INDEX_SYNCHRONIZED_LEVEL_WATER 2
#define INDEX_SOIL 3
#define INDEX_RGB_COLOR 4
#define INDEX_RGB_BRIGHTNESS 5
#define INDEX_LiGHT 6
#define INDEX_STATE 7
#define INDEX_HASPLANT 8
#define INDEX_TEMPERATURE_OUTSIDE 9
#define INDEX_HUMIDITY_OUTSIDE 10
#define INDEX_LiGHT_OUTSIDE 11
#define INDEX_LEVEL_WATER 12
#define INDEX_MAX_PUMP_POWER_TICKS 14


uint16_t memory [1000];

#define REGISTERS memory
#define REGISTER_TEMPERATURE memory[INDEX_TEMPERATURE]
#define REGISTER_HUMIDITY memory[INDEX_HUMIDITY]
#define REGISTER_SOIL memory[INDEX_SOIL]
#define REGISTER_RGB_COLOR memory[INDEX_RGB_COLOR] 
#define REGISTER_RGB_BRIGHTNESS memory[INDEX_RGB_BRIGHTNESS] 
#define REGISTER_LIGHT memory[INDEX_LiGHT]
#define REGISTER_STATE memory[INDEX_STATE]
#define REGISTER_HASPLANT memory[INDEX_HASPLANT]
#define REGISTER_TEMPERATURE_OUTSIDE memory[INDEX_TEMPERATURE_OUTSIDE]
#define REGISTER_HUMIDITY_OUTSIDE memory[INDEX_HUMIDITY_OUTSIDE]
#define REGISTER_LIGHT_OUTSIDE memory[INDEX_LiGHT_OUTSIDE]
#define REGISTER_LEVEL_WATER memory[INDEX_LEVEL_WATER]
#define REGISTER_SYNCHRONIZED_LEVEL_WATER  memory[INDEX_SYNCHRONIZED_LEVEL_WATER]
#define REGISTER_MAX_PUMP_POWER_TICKS  memory[INDEX_MAX_PUMP_POWER_TICKS]

#define BIT_STATE_RGB_POWER 0
#define BIT_STATE_RGB_MODE 1

#define BIT_STATE_FAN 2
#define BIT_STATE_HUMIDIFIER 3
#define BIT_STATE_PUMP 4
#define BIT_STATE_SERVO 5


